export const VALID_ROUTES = [
    "/",
    "/folders",
    "/templates",
    "/bookmarks",
    "/profile",
    "/contributors",
    "/admin",
    "/admin/dashboard",
    "/admin/users",
    "/admin/contributors",
    "/admin/content",
    "/admin/settings",
    "/admin/logs",
    "/admin/analytics",
    "/admin/flaggedContent",
    "/admin/login",
  ];